### PR TITLE
Updates to source & selector paths

### PR DESCRIPTION
**Pull request by AdamYee**
Hi Larry,

The recent updates to Github broke your extension. This copies source from the browser extension. Not sure why I'm seeing different code in the browser vs. what's in master.

fixes:
- For a single pull request diff view
  - change `searchStr` and `allItemsSearchStr` to `'div[data-path]'`.
- For all pull requests view
  - only sort by `.opened-by > a` (user's github handle). `.user-mention` no longer works.
  - adjust jQuery parent reference for hiding/showing user's grouped pull requests.

Updated source in the first commit. The fixing change are made in my second commit.

### CODE REVIEW

**Comment by adamburmister** [comment]
@psyrendust Laaaaarrrrryyyyy... we want your extension back! :shipit:

**Comment by psyrendust** [comment]
I'll review and test this afternoon. If it all works I'll push another update to google.

**Comment by psyrendust** [comment]
Landed as:

c1208c6
059ff07

**Comment by psyrendust** [comment]
@adamburmister @AdamYee 
Landed in chrome web store as [0.1.3](https://github.com/psyrendust/github-review-filters/releases/tag/0.1.3):
https://chrome.google.com/webstore/detail/github-review-filters/cdfbkmackojgkcohdfikiablcecbcdfa

**Pull request closed without merging**
